// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4HsFvy6qpAep50rgyStntxpI54nnXxQ',
    appId: '1:187244036891:web:63eaae9d5f7c58843409be',
    messagingSenderId: '187244036891',
    projectId: 'submission-flutter-fireb-be572',
    authDomain: 'submission-flutter-fireb-be572.firebaseapp.com',
    storageBucket: 'submission-flutter-fireb-be572.appspot.com',
    measurementId: 'G-CZ9H87NHP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaWL5nDoE0I5U_sB_aFqPy4l-ibj1Hi1A',
    appId: '1:187244036891:android:444fce76a834d0183409be',
    messagingSenderId: '187244036891',
    projectId: 'submission-flutter-fireb-be572',
    storageBucket: 'submission-flutter-fireb-be572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yORx3X96nO3GgBQyJYZrJPVuZ8U2bok',
    appId: '1:187244036891:ios:0fff4eba0dca12483409be',
    messagingSenderId: '187244036891',
    projectId: 'submission-flutter-fireb-be572',
    storageBucket: 'submission-flutter-fireb-be572.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-yORx3X96nO3GgBQyJYZrJPVuZ8U2bok',
    appId: '1:187244036891:ios:0fff4eba0dca12483409be',
    messagingSenderId: '187244036891',
    projectId: 'submission-flutter-fireb-be572',
    storageBucket: 'submission-flutter-fireb-be572.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
